name: Linting and Dead Code Audit

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  AUDIT_BRANCH: auditing
  PROJECT_SRC: FoSpy

jobs:
  setup-vars:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.vars.outputs.branch }}
      REPORT_DIR: ${{ steps.vars.outputs.report_dir }}
      RUFF_REPORT: ${{ steps.vars.outputs.ruff }}
      VULTURE_REPORT: ${{ steps.vars.outputs.vulture }}
    steps:    
      - id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          REPORT_DIR="${AUDIT_BRANCH}/${BRANCH_NAME}"
          RUFF_REPORT="${REPORT_DIR}/ruff_report.json"
          VULTURE_REPORT="${REPORT_DIR}/vulture_report.json"


          echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "report_dir=${REPORT_DIR}" >> $GITHUB_OUTPUT
          echo "ruff=${RUFF_REPORT}" >> $GITHUB_OUTPUT
          echo "vulture=${VULTURE_REPORT}" >> $GITHUB_OUTPUT


  audit:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: setup-vars
    env:
        BRANCH_NAME: ${{ needs.setup-vars.outputs.BRANCH_NAME }}
        REPORT_DIR: ${{ needs.setup-vars.outputs.REPORT_DIR }}
        RUFF_REPORT: ${{ needs.setup-vars.outputs.RUFF_REPORT }}
        VULTURE_REPORT: ${{ needs.setup-vars.outputs.VULTURE_REPORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and clear audit subfolder
        run: |
          pip install ruff vulture
          rm -rf "${AUDIT_BRANCH}"

      - name: Checkout audit branch in subfolder
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.AUDIT_BRANCH }}
          path: ${{ env.AUDIT_BRANCH }}

      - name: Lint docstrings with Ruff
        run: |
          ruff check ./${PROJECT_SRC} --output-format=json > "${RUFF_REPORT}" || true

      - name: Check for dead code with Vulture
        run: |
          vulture ./${PROJECT_SRC} --min-confidence 0 --sort-by-size > "${VULTURE_REPORT}" || true

      - name: Upload Ruff Report
        uses: actions/upload-artifact@v4
        with:
          name: ruff-report
          path: ${{ env.RUFF_REPORT }}

      - name: Upload Vulture Report
        uses: actions/upload-artifact@v4
        with:
          name: vulture-report
          path: ${{ env.VULTURE_REPORT }}

      - name: Push reports to audit branch
        run: |
          cd "${AUDIT_BRANCH}"

          git add "${BRANCH_NAME}/*"
          git commit -m "Audit reports for ${BRANCH_NAME}" || echo "No changes to commit"
          git push origin "${AUDIT_BRANCH}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
