name: Deploy MkDocs site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install FoSpy
        run: |
          pip install .

      - name: Install fos_site
        run: |
          pip install -e ./mkdocs/fos_site

      - name: Install build dependencies
        run: |
          pip install mkdocs mkdocstrings mkdocstrings-python mkdocs-copy-markdown

      - name: Check property tables and rebuild markdown stubs.
        run: |
          fos-site-build

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-build site corrections" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main back into dev
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout dev
          git merge origin/main -m "Resync dev with doc corrections" || true
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Deploy to GitHub Pages
        working-directory: mkdocs
        run: |
          mkdocs gh-deploy --force
