name: Deploy MkDocs site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install FoSpy
        run: |
          pip install .

      - name: Doc building macros
        working-directory: mkdocs/scripts
        run: |
          python _full_build.py

      - name: Install build dependencies
        run: |
          pip install mkdocs mkdocstrings mkdocstrings-python

      - name: Deploy to GitHub Pages
        working-directory: mkdocs
        run: |
          mkdocs gh-deploy --force
