name: Version Tag
on: 
  push:
    tags:
      - v*
  release:
    types:
      - released

jobs:
  check-for-main:
    name: v* tags only allowed on main branch
    runs-on: ubuntu-latest
    outputs:
      keepTag: ${{ steps.check.outputs.keepTag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check for main branch
        id: check
        run: |
          branches=$(git branch -r --contains HEAD)
          branch=${branches##*/}
          echo $branch
          keepTag=$([ "$branch" == "main" ] && echo "true" || echo "false")
          echo "keepTag=$keepTag" >> $GITHUB_OUTPUT
  
  remove-tag:
    name: Remove forbidden tag
    runs-on: ubuntu-latest
    needs: check-for-main
    if: needs.check-for-main.outputs.keepTag == 'false'
    steps:
      - name: Generate Bypass Token
        id: bypass-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.bypass-token.outputs.token }}

      - name: Debug token owner
        run: |
          curl -H "Authorization: Bearer ${{ steps.bypass-token.outputs.token }}" \
              https://api.github.com/user

      - name: Remove tag
        run: |
          git remote set-url origin https://x-access-token:${{ steps.bypass-token.outputs.token }}@github.com/${GITHUB_REPOSITORY}.git
          git push origin --delete ${{ github.ref }}

  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: check-for-main
    if: needs.check-for-main.outputs.keepTag == 'true'
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI Publish
      url: https://test.pypi.org/project/FoSpy
    permissions:
      id-token: write
    
    steps:
      - name: Download all distribution packages
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  setup-mkdocs:
    name: Setup mkdocs and mike for PyPI release.
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' &&  github.event.action == 'released' && !contains(github.event.head_commit.message, 'WORKFLOW')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          pip install mkdocs mkdocstrings mkdocstrings-python mkdocs-copy-markdown mkdocs-pygments pymdown-extensions black mike
      
      - name: Remove incoming branch
        working-directory: mkdocs
        run: |
          git config user.name mike-bot
          git config user.email github-actions[bot]@users.noreply.github.com
          git fetch origin gh-pages --depth=1
          mike delete incoming --push
      
      - name: Deploy release branch to "latest" alias
        working-directory: mkdocs
        run: |
          mike deploy $(git describe --tags --abbrev=0) latest --update-aliases --push

  publish-to-pypi:
    name: Publish to PyPI
    needs: setup-mkdocs
    runs-on: ubuntu-latest
    environment:
      name: PyPI Publish
      url: https://pypi.org/project/FoSpy
    permissions:
      id-token: write
    
    steps:
      - name: Download all distribution packages
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1