site_name: FoSpy Documentation


theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences




plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 4
- copy-markdown:
    button_text: Copy Full Page As Markdown
    button_position: top


extra_css:
  - stylesheets/extra.css

INHERIT: ./nav.yml
    
