site_name: FoSpy Documentation
site_url: https://errthumt.github.io/FoSpy/
repo_url: https://github.com/errthumt/FoSpy/
repo_name: errthumt/FoSpy

theme:
  name: material
  highlightjs: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

  features:
    - content.code.copy

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 4
          annotations_path: source
          members: true
          filters: []
- autorefs:
    resolve_closest: true
- search

extra:
  version:
    provider: mike
    alias: true

extra_css:
  - stylesheets/extra.css
  - stylesheets/plastic-dark.css
  - stylesheets/light-plus.css

INHERIT: ./nav/full.yml
    
