site_name: FoSpy Documentation

theme: readthedocs


plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 4

extra_css:
  - stylesheets/extra.css

INHERIT: ./nav.yml
    
